@baseUrl = http://localhost:8080

### List movies
GET {{baseUrl}}/movies
Accept: application/json

> {%
  client.test("Response is correct", function () {
    client.assert(response.status === 200);
    client.assert(response.body.length === 0);
  });
%}

### Create movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "imdb": "0084787",
  "title": "The Thing",
  "year": 1982
}

> {%
  client.test("Done", function () {
    client.assert(response.status === 204);
  });
%}

### Find created movie
GET {{baseUrl}}/movies/0084787
Accept: application/json

> {%
  client.test("Done", function () {
    client.assert(response.status === 200);
    client.assert(response.body.imdb === "0084787");
  });
%}

### Update movie
PUT {{baseUrl}}/movies/0084787
Content-Type: application/json

{
  "imdb": "0084787",
  "title": "The Thing",
  "year": 1982,
  "casts": [
    "Kurt Russell",
    "Wilford Brimley"
  ]
}

> {%
  client.test("Done", function () {
    client.assert(response.status === 204);
  });
%}

### Find updated movie
GET {{baseUrl}}/movies/0084787
Accept: application/json

> {%
  client.test("Done", function () {
    client.assert(response.status === 200);
    client.assert(response.body.casts[0] == "Kurt Russell");
    client.assert(response.body.casts[1] == "Wilford Brimley");
  });
%}

### Delete movie
DELETE {{baseUrl}}/movies/0084787

> {%
  client.test("Done", function () {
    client.assert(response.status === 204);
  });
%}

### Find deleted movie
GET {{baseUrl}}/movies/0084787
Accept: application/json

> {%
  client.test("Done", function () {
    client.assert(response.status === 404);
  });
%}
