[flyway]
cleanDisabled = false

[environments.local]
url = "jdbc:postgresql://localhost:5432/movies"
user = "admin"
password = "s3cr3t"
[environments.docker]
url = "jdbc:postgresql://pg:5432/movies"
user = "admin"
password = "s3cr3t"
